name: fix license headers

on: [push, pull_request]
      
jobs:
  fix-license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: fix headers
        uses: apache/skywalking-eyes/header@v0.7.0
        with:
          mode: fix
          
      - name: apply changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'    